<?php

require('../fpdf.php');
require '../../model/DB/TablaReportesDbModelClass.php';
require '../../model/DB/TablaLoteEstandarDbModelClass.php';
require '../../model/DB/TablaLoteReactivoDbModelClass.php';
require '../../model/DB/TablaEnsayoEquipoDbModelClass.php';
require '../../model/DbClass.php';
require_once '../rotation.php';
$perfil = $_POST['idPerfil'];

class PDF extends FPDF {

    public $muestra;
    public $cuadroControlValoracion = false;
    public $cuadroControlDisolucion = false;
    public $cuadroControlPureza = false;

    function RotatedText($x, $y, $txt, $angle) {
//Text rotated around its origin
        $this->Rotate($angle, $x, $y);
        $this->Text($x, $y, $txt);
        $this->Rotate(0);
    }

    function Header() {
//Logo
        $this->Cell(40, 20, utf8_decode(''), 1, 0, 'C');
        $this->Image('../../views/images/logoEmpresa.png', 15, 13, 30);
        $this->SetFont('Arial', 'B', 11);

        $this->Cell(80, 20, utf8_decode('HOJA DE TRABAJO ANALÍTICO'), 1, 0, 'C');

        $this->SetFont('Arial', 'B', 7);
        $this->Cell(30, 5, utf8_decode('Código'), 1, 0, 'C');
        $this->Cell(30, 5, utf8_decode('F-145-(LA-008)'), 1, 0, 'C');
        $this->SetXY(130, 15);
        $this->Cell(30, 5, utf8_decode('Versión'), 1, 0, 'C');
        $this->Cell(30, 5, utf8_decode('01'), 1, 0, 'C');
        $this->SetXY(130, 20);
        $this->Cell(30, 5, utf8_decode('Vigente Desde'), 1, 0, 'C');
        $this->Cell(30, 5, utf8_decode('06-02-17'), 1, 0, 'C');
        $this->SetXY(130, 25);
        $this->Cell(30, 5, utf8_decode('Página'), 1, 0, 'C');
        $this->SetTextColor(255, 0, 0); //Rojo
        $this->Cell(30, 5, utf8_decode('ANEXO'), 1, 0, 'C');
        $this->Ln(5);
        $this->Cell(180, 10, '', 0, 0, 'C');
        $this->Ln(5);

// Marca de agua
        if ($GLOBALS['perfil'] == "false") {
            $this->SetFont('Arial', 'B', 14);
            $this->SetTextColor(255, 192, 203);
            for ($i = 0; $i < 1000; $i += 30) {
                $this->RotatedText(0, $i, 'H O J A   D E   T R A B A J O   P A R C I A L   C O P I A   N O   C O N T R O L A D A    H O J A   D E   T R A B A J O   P A R C I A L   C O P I A   N O   C O N T R O L A D A', 45);
            }
        }
    }

    function Footer() {
// Position at 1.5 cm from bottom
        $this->SetY(-25);
        $this->SetFont('Arial', 'B', 6);
        $this->Ln();
        $this->Cell(100, 5, utf8_decode('Página ') . $this->PageNo() . ' de {nb}', 0, 0, 'R');
    }

    function obtenerInformacionGeneral() {
        $dato = $_POST['idMuestra'];


        $modelReporte = new TablaReportesDbModelClass();
        $this->muestra = $modelReporte->getInfoPrincipalHR($dato)[0];

        $this->muestra['metodos'] = $modelReporte->getMetodosHR($dato)[0];
        $this->muestra['ensayosRealizar'] = $modelReporte->getEnsayosARealizarHR($dato)[0];
        $this->muestra['clienteid'] = $modelReporte->getidCliente($dato)[0];
        $this->muestra['numeroCliente'] = $modelReporte->numeroCliente($dato)[0];
        $this->muestra['ensayos'] = $modelReporte->VerHojadeRuta($dato);
    }

    function informacionMuestra() {
        if (strstr($this->muestra['ensayosRealizar']['ensayosarealizar'], "Traza")) {
            $this->muestra['ensayosRealizar'] = 'Análisis de Trazas ';
        }
        $fechaLlegada = new DateTime($this->muestra['fecha_llegada']);

        $this->muestra['des_area_analisis'];
        $this->SetFont('Arial', '', 9);
        $this->SetFillColor(169, 169, 169);
        $this->RoundedRect($this->GetX(), $this->GetY() + 2, 180, 6, 2, 'S', '12');

        $this->Ln(-20);
        $this->SetFont('Arial', 'B', 7);
        $this->Cell(180, 50, utf8_decode('HOJA DE TRABAJO ANALíTICO ' . strtoupper($this->muestra['FormaFarmaceutica']) . ' ' . ($this->muestra['nombre_producto'])), 0, 0, 'C');
        $this->Ln(28);
        $this->Cell(25, 7, 'F. DE INGRESO', 1, 0, 'C');
        $this->Cell(25, 7, utf8_decode('F.ANÁLISIS'), 1, 0, 'C');
        $this->Cell(30, 7, 'LQF', 1, 0, 'C');
        $this->Cell(100, 7, 'Lote', 1, 0, 'C');
        $this->Ln();
        $this->SetFont('Arial', '', 9);
        $this->Cell(25, 7, $fechaLlegada->format('d-m-y'), 1, 0, 'C');
        $this->Cell(25, 7, '', 1, 0, 'C');
        //Por solicitud de CARLOS se cambia prefijo y se ajusta según lo solicitado LQF-#-yy
        $this->Cell(30, 7, 'LQF-' . substr($this->muestra['numeroCliente']['elnum'], 6, 4) . '-' . $fechaLlegada->format('y'), 1, 0, 'C');
        $this->Cell(100, 7, utf8_decode($this->muestra['lote']), 1, 0, 'C');
        $this->SetFont('Arial', 'B', 9);
        $this->Ln();
        $this->Cell(180, 7, utf8_decode($this->muestra['nombre_producto']), 1, 0, 'C');
        $this->Ln(10);

        $this->SetLineWidth(0.1);
        $this->SetDrawColor(169, 169, 169);
        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(6);

        $this->SetFont('Arial', '', 10);
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Cell(6, 6, utf8_decode(''), 1, 0, 'C');
        $this->Ln(10);


        $this->SetFont('Arial', '', 10);
        $this->SetDrawColor(0, 0, 0);
        $this->Cell(180, 15, utf8_decode('Analizado por: ______________________________        Aprobado por: _______________________________'), 1, 0, 'L');
        $this->Ln(10);
    }

}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->obtenerInformacionGeneral();
$pdf->informacionMuestra();

$pdf->Output();
?>
